### ISSUE TITLE
List online users OR valid sessions? 

### ISSUE THREAD

**Issue by thiagotalma** [bscheshirwork/yii2-redis-session#1]
Hi @bscheshirwork ! Good job! 

Please correct me if I am wrong, but the online user list does not faithfully represent users who are actually browsing the system, right?

The list actually shows the sessions that remain valid, even though the User has left the site for hours, right?

**Comment by bscheshirwork** [comment]
`getOnlineUser` return the array indexed by `userIdentity` `id`.  
Values of this array is a last visit user timestamp (don't forgot set timezone in the `\Yii::$app->timeZone` application property).  
Select already filtered only if `timestamp` in `[ time() .. time() - ini_get('session.gc_maxlifetime')]`

i.e. PHP settings `session.gc_maxlifetime` (typically the default is 24 minutes (1440 seconds) http://www.php.net/manual/en/session.configuration.php) set max range of selection, but your can be sort/filter result of `getOnlineUser` by timestamp values as you wish.
