### ISSUE TITLE
Unknown component ID: redis

### ISSUE THREAD

**Issue by bianqui149** [bscheshirwork/yii2-redis-session#4]
hey i am new in yii2, i am paste this in the config.php: 
'session' => [ 'class' => 'bscheshirwork\redis\Session'],
and this in the view: <?php \Yii::$app->session->getOnlineUsers();?>
i am getting this error Unknown component ID: redis

**Comment by bscheshirwork** [comment]
@bianqui149 You can install (or add docker container) redis (see [advanced template](https://github.com/bscheshirwork/docker-yii2-app-advanced-redis)) and configure it.

> Redis Session implements a session component using [redis](http://redis.io/) as the storage medium.
> It needs to be configured with a redis [[Connection]] that is also configured as an application component.
> By default it will use the `redis` application component.

> Based on [yii2-redis](https://github.com/yiisoft/yii2-redis) session. 

To use this extension, you have to configure the Connection class in your application configuration:
```php
return [
    //....
    'components' => [
        'redis' => [
            'class' => 'yii\redis\Connection',
            'hostname' => 'localhost',
            'port' => 6379,
            'database' => 0,
        ],
    ]
];
```
