### ISSUE TITLE
Conflicting time() on zadd in writeSession()

### ISSUE THREAD

**Issue by andrejs-uibo** [bscheshirwork/yii2-redis-session#5]
Hi,
If multiple calls are made to `Session::writeSession() `method at the same time, then `zadd()` fails and returns `false`, since the `time() `is identical. 

The `session_write_close()` is called and this results in a php notice message:

`[php7:notice] PHP Warning:  session_write_close(): Failed to write session data using user defined save handler. (session.save_path: /var/lib/php/sessions) in /var/www/html/proj/vendor/yiisoft/yii2/web/Session.php on line 187`
`[php7:notice] PHP Stack trace:`
`[php7:notice] PHP   1. yii\\web\\ErrorHandler->handleException($exception = *uninitialized*) /var/www/html/proj/vendor/yiisoft/yii2/base/ErrorHandler.php:0`
`[php7:notice] PHP   2. bscheshirwork\\redis\\Session->close() /var/www/html/proj/vendor/yiisoft/yii2/web/Session.php:0`
`[php7:notice] PHP   3. session_write_close() /var/www/html/proj/vendor/yiisoft/yii2/web/Session.php:187`

As a quick workaround, I used this instead of `time()`:

` $time = (string)microtime(true);`

**Comment by bscheshirwork** [comment]
resolved on ac6d4119b7c07efeb874dbfd685faef53a93cc70

@thiagotalma we have changes in a keys of online users

**Comment by thiagotalma** [comment]
@bscheshirwork I did not understand...  😕

**Comment by bscheshirwork** [comment]
@thiagotalma so... In this case... Nothing matter :smile_cat:

**Comment by abbosxon** [comment]
Hello! I installed bscheshirwork/yii2-redis-session. 
But does not work
`\Yii::$ app->session->getOnlineUsers ();`
`\Yii::$ app->session->getSessionsById ($ userIdentityId);`
`\Yii::$ app->session->destroyUserSessions ($ userIdentityId);`
`\Yii::$ app->session->getActiveSessions ();` functions. 
There is no difference from yii\redis\Session
