### ISSUE TITLE
Functionals not working

### ISSUE THREAD

**Issue by abbosxon** [bscheshirwork/yii2-redis-session#6]
Hello! 
I installed bscheshirwork/yii2-redis-session. 
But does not work
`\Yii::$ app->session->getOnlineUsers();`
`\Yii::$ app->session->getSessionsById($userIdentityId);`
`\Yii::$ app->session->destroyUserSessions($userIdentityId);`
`\Yii::$ app->session->getActiveSessions();`
functions.
There is no difference from yii\redis\Session

**Comment by abbosxon** [comment]
Functional returned empty array

**Comment by bscheshirwork** [comment]
@abbosxon It's not cool! 

So... I can propose some steps to help of localizing problem for you:

You have any errors or notice in logs? 
User can login?
You use yii\redis\Session on this application before?
You can try to check you config again - may be
```
       'session' => [
           'class' => 'bscheshirwork\redis\Session',
       ],
```
 will be rewrite otherwhere later as `yii\redis\Session`?

Anyway I have no idea what happens without more info about config and composer info.

**Comment by bscheshirwork** [comment]
Look like stale for me

**Comment by vprivaloff** [comment]
> Functional returned empty array

Hey!) You have to initialize the $keyPrefix property, so you end up with an empty array since the mask does not match the current prefix. Sorry for offtopic
